### ISSUE TITLE
Операторы в php

### ISSUE THREAD

**Issue by olegpopadko** [VSiniy/senseiOleg#11]
В чем отличие операторов сравнения == и ===?
В чем отличие логических операторов && и and, || и or?

**Comment by olegpopadko** [comment]
Почему issue закрыта?

**Comment by VSiniy** [comment]
Различие заключается в приоритетах данных операторов
Оператор || имеет больший приоритет, чем or (соответственно с && и and) из чего следует, что при использовании данныого оператора в связке с присваиванием сначала выполнится сравнение $var = ($a || $b), а при использовании or будет следующий порядок ($var = $a) or $b.

**Comment by olegpopadko** [comment]
Где взял?

**Comment by VSiniy** [comment]
инет

**Comment by olegpopadko** [comment]
```php
$a = false or true;
```
Какое значение в $a?

**Comment by VSiniy** [comment]
false

**Comment by olegpopadko** [comment]
```php
$fruits = [null];
$fruits = array_pop($fruits) or $fruits = ['apple'];
```
Без интерпретатора. Что будет в $fruits?

**Comment by VSiniy** [comment]
$fruits[0] = "apple"

**Comment by olegpopadko** [comment]
Правильный ответ
```php
array(1) {
  [0] =>
  string(5) "apple"
}
```

Выполнено
