### ISSUE TITLE
Кнопка редактировать

### ISSUE THREAD

**Issue by olegpopadko** [VSiniy/senseiOleg#3]
Не должно быть кнопки общей "редактировать". Возле каждой записи должна быть отдельная  кнопка, которая должна вести на форму.

**Comment by olegpopadko** [comment]
То же самое и с кнопкой удалить

**Comment by VSiniy** [comment]
И это

**Comment by olegpopadko** [comment]
что за несвязный комментарий?

**Comment by VSiniy** [comment]
ох
я имел ввиду, что и это можно закрыть, наверно

**Comment by olegpopadko** [comment]
Выполнено
