### ISSUE TITLE
Big file

### ISSUE THREAD

**Issue by olegpopadko** [VSiniy/senseiOleg#5]
Generate a file with size of about 4 GB (maybe with other php script)

**Comment by VSiniy** [comment]
Я создал текстовый файл на 4Гб, но его не смог открыть даже Sublime Text.
Браузером файл так же не обрабатывается.
После уменьшения размера файла до 100Мб браузер его так же не открывает.
Сейчас тестирую файл на 2.1Мб, все работает как надо, имеется 132193 записи. Имеют место тормоза не только браузера во время загрузки, но и всей системы.

**Comment by VSiniy** [comment]
Код работает и при нашрузке в виде файла с данными пользователей большого размера

**Comment by olegpopadko** [comment]
Сделано
