### ISSUE TITLE
Навигация

### ISSUE THREAD

**Issue by olegpopadko** [VSiniy/senseiOleg#7]
https://github.com/VSiniy/senseiOleg/commit/750a8c65163f1d087fee3210f8e64bb691e1a5a9#commitcomment-9467120

https://github.com/VSiniy/senseiOleg/commit/109d40088d670bc47ab36c99fd6ac7959bc29ccb

**Comment by VSiniy** [comment]
Было переписано под ссылку.

**Comment by olegpopadko** [comment]
https://github.com/VSiniy/senseiOleg/commit/750a8c65163f1d087fee3210f8e64bb691e1a5a9#diff-7a4890d46ddfbe51bdcf97f988b8df7a
Не исправлено

**Comment by VSiniy** [comment]
Не обновил этот файл.
Исправлено.

**Comment by olegpopadko** [comment]
Выполнено
