### ISSUE TITLE
Определение метода запроса

### ISSUE THREAD

**Issue by olegpopadko** [VSiniy/senseiOleg#9]
По всему проекту post запросы определяются кодом типа - 
```php
if ($_POST == null)
```
Это неверно. Отыскать верный вариант и исправить.

**Comment by VSiniy** [comment]
Было исправлено на if (is_null($_POST["add"])) для файла add.php и
if (is_null($_POST["edit"])) для файла edit.php

**Comment by olegpopadko** [comment]
Еще хуже чем было

**Comment by VSiniy** [comment]
Чуви, тогда нужна твоя подсказка.

**Comment by olegpopadko** [comment]
Не понимаешь основ HTTP.
https://github.com/VSiniy/senseiOleg/issues/1

**Comment by VSiniy** [comment]
Изменено на if ($_POST)

**Comment by olegpopadko** [comment]
http://lmgtfy.com/?q=php+detect+request+method

**Comment by VSiniy** [comment]
Исправлено

**Comment by olegpopadko** [comment]
Выполнено
